version: '3'

volumes:
  static_foodgram:
  media_foodgram:
  postgres_data_foodgram:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_foodgram:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  backend:
    image: eminencesaul/foodgram_backend:latest
    volumes:
      - static_foodgram:/app/static/
      - media_foodgram:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: eminencesaul/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_foodgram:/var/html/static/
      - media_foodgram:/var/html/media/
    depends_on:
      - backend
